version: '3.9'

services:
  database:
    image: postgres
    container_name: base-api-node
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    # restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
